{% set name = "startables" %}
{% set version = "0.8.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc34f48f8194a71895f0502551845e7edee5cc88d123f6598461176c9d9a2ad9

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy
    - pandas
    - openpyxl

test:
  requires:
    - pytest
  imports:
    - startables

about:
  home: https://github.com/startable/startables-python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Reads, writes, and manipulates data stored in StarTable format
  description: |
    Python package with data structures and functionality to read/write files 
    in StarTable format and contain and manipulate the information therein.  
  doc_url: https://github.com/startable/startables-python
  dev_url: https://github.com/startable/startables-python

extra:
  recipe-maintainers:
    - jfcorbett
    - heidikira
    - guilhermebs
