travis:
  secure:
    BINSTAR_TOKEN: Sp4XvxvbkOeQgRf5FWCuvupsLCWY7BzHMpiXUmyWvXSTs2/ic3m9K3URnJ3HKIjZ2BL6aBcTN+Rry6A7dMqDqc9wvuJO8ddZHF+6erA5ifAAnbrLzFT2V2fsWjy0YOTFs7GbyUaM0TSzaRelf+43Q82WL3pMSWM3sLn0wugHBFsZuS4/IWR5+7/fuQaeEEtWjkZtB6FqTc/Pt+ijyU5ec8mGPdcLGCdFZrD7MvozmuK/LMXbPxGLeVr7lw5fHKlDHY6MEVTymXnnMPXS9iOGFGuTNK1E2OSsLB9J1p5Vey6PeUTgMWFvYt5Ol3xVLMbKc6vGOI0Z50PjQYPDtPhMTQYrr/9Otufcbr+3tUcwGE0CY5e6BkDKL7axAN41t1/jBbMCCOMZ3YI2ufwUREg5shNz+I2k7IG14FCEBQyEm96+VzLpcULVgOkNn4pMY6unObLpd/BflToNR8y1EjuYMQJpgfdzh0Yd37iO1jDPhA2RyKJZcv4n2TgSNDCmbzdH9fKJd0lyAGKQDCDgP1cJfEAvdDTE4HseWQKO/PYkg1BIPT3ZZxHEECs3Sq0PmdLLtx3qsEkE0dCtg22i8/95c23rfODzdC4jm+6DP81/TSzQc8Kwb7THSHuNXPkawzlTQ8QiXVP2hL78W7RnhjYSS7G+4vrlDoxl4nKVhw4/VO8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
